##################################################################################
# METRA Ant Unsupervised Pretraining
##################################################################################

project_name: 'FlashRL'
entity_name: 'draftrec'
group_name: 'metra_ant_pretrain'
exp_name: 'ant_skill_pretrain'
seed: 0

logger_type: 'tensorboard'
save_path: 'models/${group_name}/${exp_name}/${env.env_name}/seed${seed}-TIMESTAMP'
agent_load_path: null
buffer_load_path: null

##################################################################################
# Environment
##################################################################################

num_env_steps: 6_000_000
num_train_envs: 8
num_eval_envs: 1
num_record_envs: 1

num_eval_episodes: 1
num_record_episodes: 0

##################################################################################
# Training
##################################################################################

gamma: 0.99
n_step: 1

# Total training duration in environment steps.
num_interaction_steps: ${eval:'${num_env_steps} / (${num_train_envs})'}

# Update schedule. Changing num_env_steps will not affect these ratios/intervals.
# With num_train_envs=8 and env_steps_per_update=160, we run 0.05 updates per interaction step.
env_steps_per_update: 160
updates_per_interaction_step: ${eval:'${num_train_envs} / ${env_steps_per_update}'}
num_update_steps: ${eval:'${num_env_steps} / ${env_steps_per_update}'}

# Logging / evaluation / checkpoint cadence in environment steps.
evaluation_interval_env_steps: 10_000
metrics_interval_env_steps: 10_000
logging_interval_env_steps: 10_000
save_checkpoint_interval_env_steps: 100_000

evaluation_per_interaction_step: ${eval:'max(1, int(${evaluation_interval_env_steps} / ${num_train_envs}))'}
metrics_per_interaction_step: ${eval:'max(1, int(${metrics_interval_env_steps} / ${num_train_envs}))'}
recording_per_interaction_step: null
logging_per_interaction_step: ${eval:'max(1, int(${logging_interval_env_steps} / ${num_train_envs}))'}
save_checkpoint_per_interaction_step: ${eval:'max(1, int(${save_checkpoint_interval_env_steps} / ${num_train_envs}))'}
save_buffer_per_interaction_step: null
max_checkpoints_to_keep: 1

defaults:
- agent: metra_ant_pretrain
- env: mujoco
- _self_

env:
  env_name: 'Ant-v4'
  # env_name: 'HalfCheetah-v4'