##################################################################################
# Mujoco
##################################################################################

env_type: 'mujoco'
env_name: 'Ant-v4'
num_env_steps: ${num_env_steps}

seed: ${seed}
num_train_envs: ${num_train_envs}
num_eval_envs: ${num_eval_envs}
num_record_envs: ${num_record_envs}
rescale_action: true
max_episode_steps: 1000