skill_dim: 2
model_master_dim: 1024
model_master_num_layers: 2


spectral_normalization: False

dual_lam: 30
alpha: 0.01
common_lr: 1e-4
gamma: 0.99

buffer_max_length: 300000
buffer_min_length: 10000
sample_batch_size: 256

target_coef: 1.0

dual_slack: 1e-3
discount: 0.99
tau: 0.005