##################################################################################
# METRA
##################################################################################

agent_type: 'metra'

seed: ${seed}

normalize_reward: true
normalized_G_max: 5.0

asymmetric_observation: false
device_type           : 'cuda'

buffer_max_length : 1_000_000
buffer_min_length : 10_000
buffer_device_type: 'cpu'
sample_batch_size : 2048

# learning rate
sac_scheduler_type : 'cosine'
sac_lr_init_value  : 3e-4
sac_lr_peak        : 3e-4
sac_lr_end_value   : 1.5e-4
sac_lr_warmup_rate : 1e-6
sac_lr_warmup_steps: ${eval:'int(${agent.sac_lr_warmup_rate} *
  ${num_interaction_steps} * ${updates_per_interaction_step})'}
sac_lr_decay_rate : 1.0
sac_lr_decay_steps: ${eval:'int(${agent.sac_lr_decay_rate} *
  ${num_interaction_steps} * ${updates_per_interaction_step})'}

actor_num_blocks    : 2
actor_hidden_dim    : 128
actor_bc_alpha      : 0.0
actor_noise_zeta_mu : 2.0
actor_noise_zeta_max: 16
actor_update_period : 2

critic_num_blocks       : 2
critic_hidden_dim       : 256
critic_num_bins         : 101
critic_min_v            : ${eval:'-${agent.normalized_G_max}'}
critic_max_v            : ${eval:'${agent.normalized_G_max}'}
critic_target_update_tau: 0.01

temp_initial_value : 0.01
temp_target_sigma  : 0.15
temp_target_entropy: null

gamma : ${gamma}
n_step: ${n_step}

use_compile : false
compile_mode: 'reduce-overhead'
use_amp     : true

load_optimizer        : true
load_reward_normalizer: false

encoder_scheduler_type : 'constant'
encoder_lr_init_value  : 1e-4
encoder_lr_peak        : 1e-4
encoder_lr_end_value   : 5e-5
encoder_lr_warmup_rate : 1e-6
encoder_lr_warmup_steps: ${eval:'int(${agent.encoder_lr_warmup_rate} *
  ${num_interaction_steps} * ${updates_per_interaction_step})'}
encoder_lr_decay_rate : 1.0
encoder_lr_decay_steps: ${eval:'int(${agent.encoder_lr_decay_rate} *
  ${num_interaction_steps} * ${updates_per_interaction_step})'}

lambda_scheduler_type : 'constant'
lambda_lr_init_value  : null
lambda_lr_peak        : 1e-4
lambda_lr_end_value   : null
lambda_lr_warmup_steps: null
lambda_lr_decay_steps : null

encoder_type             : 'flash'
skill_type               : 'continuous'
skill_dim                : 2
skill_encoder_hidden_dim : 256
skill_encoder_num_layers : 2
skill_encoder_weight_norm: false

dual_lambda_init_value: 30.0

constraint_epsilon: 1e-3

use_encoder_to_update: true
default_skill_x: 1.0
default_skill_y: 0.0
default_skill_index: 0